### ISSUE TITLE
[Fable] setup to-do

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/ISADotNet#90]
- [ ] Test full release chain
  - [x] successful tests
  - [ ] bundle as npm package
  - [ ] nuget package
  - [ ] Automated release to both npm and nuget? Only as flag?
- [x] github action tests on commit to main or PR to main
- [ ] Code coverage? 
  - [ ] dotnet
  - [ ] js?
- [x] make package.json include both `ISADotNet` and `ISADotNet.Json`
https://github.com/nfdi4plants/ISADotNet/blob/35539e7a7a8d2d5acf1b9a647b933c5120f9c5c7/package.json#L7

**Comment by Freymaurer** [comment]
Does it make sense to work on the open tasks when the possible repo restructuring is in sight? @kMutagene @omaus @HLWeil

**Comment by HLWeil** [comment]
I think working on the packaging and stuff doesn't really make sense. But it would definitely be a possibility to finish up the fable transpilation of the ISADotNet.XLSX project. Then we could be sure that the 3 core libraries are fable-ready.

**Comment by kMutagene** [comment]
@Freymaurer setting up / getting to know reproducible workflows for test coverage in both .NET and js would be something we can always benefit from, actually implementing stuff should wait imo (other than what @HLWeil mentioned)
